---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: database
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: redis
      version: 17.16.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    values:
      auth:
        enabled: false
      master:
        persistence:
          enabled: false
      architecture: standalone
      replica:
        replicaCount: 0
      metrics:
        enabled:
          serviceMonitor:
            enabled: true
            interval: 1m
