---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${SECRET_ACME_EMAIL}
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: ${SECRET_ACME_EMAIL}
            apiKeySecretRef:
              name: cloudflare-secret
              key: api-key
        selector:
          dnsZones:
            - ${SECRET_DOMAIN}
---
# yamllint disable-line rule:line-lengths
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${SECRET_ACME_EMAIL}
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ${SECRET_ACME_EMAIL}
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: ${SECRET_ACME_EMAIL}
            apiKeySecretRef:
              name: cloudflare-secret
              key: api-key
        selector:
          dnsZones:
            - ${SECRET_DOMAIN}
