---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./media-pvc.yaml
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./autobrr/ks.yaml
  - ./media-browser/ks.yaml
  - ./overseerr/ks.yaml
  # - ./sonarr/ks.yaml
  - ./wizarr/ks.yaml
