---
version: "3"

vars:
  CLUSTER_DIR: "{{.ROOT_DIR}}/kubernetes"
  CLUSTER_SECRETS_FILE: "{{.CLUSTER_DIR}}/flux/vars/cluster-secrets.sops.env"
  CLUSTER_SETTINGS_FILE: "{{.CLUSTER_DIR}}/flux/vars/cluster-settings.env"

env:
  KUBECONFIG: "{{.ROOT_DIR}}/kubeconfig"
  SOPS_AGE_KEY_FILE: "{{.ROOT_DIR}}/age.key"
  K8S_AUTH_KUBECONFIG: "{{.ROOT_DIR}}/kubeconfig"

includes: {}

tasks:
  default:
    silent: true
    cmds: ["task -l"]

  flux-apply:
    desc: Apply a resource path that contains Flux substitution variables
    dotenv: ['{{.CLUSTER_SETTINGS_FILE}}']
    vars:
      ks: '{{ or .ks (fail "Missing path (`ks` var)") }}'
    cmd: |
      sops exec-env {{.CLUSTER_SETTINGS_FILE}} \
        "kustomize build --load-restrictor=LoadRestrictionsNone {{.ks}} | \
          envsubst | kubectl apply --server-side --field-manager=kustomize-controller -f -"
    preconditions:
      - sh: test -f {{.CLUSTER_SECRETS_FILE}}
      - sh: test -f {{.CLUSTER_SETTINGS_FILE}}

  # https://github.com/fluxcd/helm-controller/issues/644
  "644":
    cmds:
      - kubectl -n {{.namespace}} delete secret -l owner=helm,name={{.release}},status=pending-upgrade
      - flux -n {{.namespace}} reconcile hr {{.release}}
    vars:
      release: '{{ or .release (fail "HelmRelease `release` is required") }}'
      namespace: '{{.namespace | default "default"}}'
    preconditions:
      - flux -n {{.namespace}} get hr {{.release}}
