---
version: "3"

vars:
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"

env:
  KUBECONFIG: "{{.ROOT_DIR}}/kubeconfig"
  SOPS_AGE_KEY_FILE: "{{.ROOT_DIR}}/age.key"

includes:
  cluster: .taskfiles/ClusterTasks.yaml
  flux: .taskfiles/FluxTasks.yaml

tasks:
  default: task -l
