---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lldap-gatus-ep
  namespace: security
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: requests
        group: internal
        ui:
          hide-hostname: true
          hide-url: true
        url: http://overseerr.media.svc.cluster.local:8000
        headers:
          Host: requests.janpuc.com
        interval: 1m
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
