---
web:
  port: ${CUSTOM_WEB_PORT}
storage:
  type: postgres
  path: postgres://${INIT_POSTGRES_USER}:${INIT_POSTGRES_PASS}@${INIT_POSTGRES_HOST}:5432/${INIT_POSTGRES_DBNAME}?sslmode=disable
  caching: true
metrics: true
debug: false
ui:
  title: Status | Gatus
  header: Status
alerting:
  pushover:
    application-token: ${CUSTOM_PUSHOVER_APP_TOKEN}
    user-key: ${CUSTOM_PUSHOVER_USER_KEY}
    default-alert:
      description: health-check failed
      send-on-resolved: true
      failure-threshold: 5
      success-threshold: 2
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m
endpoints:
  - name: status
    group: external
    ui:
      hide-hostname: true
      hide-url: true
    url: https://status.${SECRET_DOMAIN}
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover
  - name: ${ADDITIONAL_MONITORING_NAME_1}
    group: remote
    ui:
      hide-hostname: true
      hide-url: true
    url: https://${ADDITIONAL_MONITORING_DOMAIN_1}
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover
  - name: ${ADDITIONAL_MONITORING_NAME_2}
    group: remote
    ui:
      hide-hostname: true
      hide-url: true
    url: https://${ADDITIONAL_MONITORING_DOMAIN_2}
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover
  - name: ${ADDITIONAL_MONITORING_NAME_3}
    group: remote
    ui:
      hide-hostname: true
      hide-url: true
    url: https://${ADDITIONAL_MONITORING_DOMAIN_3}
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover
  - name: ${ADDITIONAL_MONITORING_NAME_4}
    group: remote
    ui:
      hide-hostname: true
      hide-url: true
    url: https://${ADDITIONAL_MONITORING_DOMAIN_4}
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover
