---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: csi-s3
  namespace: kube-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: csi-s3-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
  data:
    - secretKey: accessKeyID
      remoteRef:
        key: csi-s3
        property: ACCESS_KEY_ID
    - secretKey: secretAccessKey
      remoteRef:
        key: csi-s3
        property: SECRET_ACCESS_KEY
    - secretKey: endpoint
      remoteRef:
        key: csi-s3
        property: ENDPOINT
