# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: csi-s3-secret
    namespace: kube-system
stringData:
    accessKeyID: ENC[AES256_GCM,data:ifv613TVpdWEd6VIfRnqqtIbCetlMl9z3YGbReVgfls=,iv:o1R9Z8G9jKLlWjqXS+3eu3QMX56qekEEHz55iVs4lUk=,tag:yKU+mxj5MlZLuAKm31g8pw==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:uZXgtM9DFeNBOte9nk/YYVpz4RtKJO1wIhLn4ybEcyU=,iv:tF7AXHYI7gLUyFh9nNcg8u5bU7dR2vv++5SBPORAsHY=,tag:XvTNc+8VV8WjB/gXpgPR7g==,type:str]
    endpoint: ENC[AES256_GCM,data:ET9k1Cf36WSPUMy7Kvk/CUeNAhG0MW2T9Hlexdrr,iv:c6zWfHgQdlR0J0XHUPz9st6X59nxe/H312QVpLS8L0o=,tag:94XcW2KOkW/O+2M9AxBjQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1myxsdyjgwefpljpsvf0n6pvjr4n9ygz0nh3zy7wkfjnqdg54jayqwaqqfm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWjBlOTlhQnNFWDErQlM0
            ejBKYXpLTXRMN1JDWUJHL3F1R2FSU2ZaR0JvCkFaak1GdCswbWRuOEVJTXA3cFNi
            UC8zdDNidEZ6Rkp5bjQ5dTBhL0Rod0UKLS0tIHFHOE5VZDU4b01SeTZEVkdaemFW
            UU0yVGJ3N3NSYVlsVXZScGNvOHY5WjQKP0duP4eKEsD+GslnxYYwe4OGSIb/pa0T
            UoWNbAVKcl7eTM3lpAcq/bW8pofkRqHNEbO2j3mR0B78Oc9aRnYwIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T12:47:09Z"
    mac: ENC[AES256_GCM,data:Er+uKS4/9iOV9zpyNmKXU4TS2k9XhLWP5AcmAw6wcq/I3CUbBAwGXVlNoy2HtLCiWwLrwqT2tovCNdQJ2Devq3Tnz1baFTaiTowYZUJTDs+sEC1+6tvJZXWvASNC2Wm0QOaMXf1C7qPKG9U9f5x/yYvBnNHsarONOSTJwn5HhMU=,iv:onRAdBk4aeqbGX63Z3QOMrPd4lEZV6AgCV30UQ2A/wM=,tag:fYtTIth6RAkSzgECqWQRMw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
