---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-gatus-ep
  namespace: security
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: authelia
        group: external
        ui:
          hide-hostname: true
          hide-url: true
        url: https://auth.janpuc.com
        interval: 1m
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
