---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forwardauth-authelia
  namespace: security
spec:
  forwardAuth:
    address: http://authelia.security.svc.cluster.local/api/verify?rd=https://auth.${SECRET_DOMAIN}
    trustForwardHeader: true
    authResponseHeaders:
      - Remote-User
      - Remote-Name
      - Remote-Email
      - Remote-Groups
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: headers-authelia
  namespace: security
spec:
  headers:
    browserXssFilter: true
    customFrameOptionsValue: "SAMEORIGIN"
    customResponseHeaders:
      Cache-Control: "no-store"
      Pragma: "no-cache"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: chain-authelia-auth
  namespace: security
spec:
  chain:
    middlewares:
      - name: forwardauth-authelia
        namespace: security
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: chain-authelia
spec:
  chain:
    middlewares:
      - name: headers-authelia
        namespace: security
