---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: authelia
  namespace: security
spec:
  minVersion: VersionTLS12
  maxVersion: VersionTLS13
  cipherSuites:
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_RSA_WITH_AES_256_GCM_SHA384
