---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: openebs
      version: 3.9.0
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultStorageConfig:
      enabled: "false"
    varDirectoryPath:
      baseDir: "/var/openebs"
    localprovisioner:
      basePath: "/var/openebs/local"
    nfs-provisioner:
      enabled: true
