---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: 24.0.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      tag: v3.0.0-beta3
    service:
      annotations:
        io.cilium/lb-ipam-ips: ${SINGLE_NODE_PRIVATE_IP}
    env:
      - name: CF_DNS_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-secret
            key: api-token
    tlsStore:
      default:
        defaultGeneratedCert:
          resolver: letsencrypt-production
          domain:
            main: ${SECRET_DOMAIN}
            sans:
              - ${SECRET_DOMAIN}
              - "*.${SECRET_DOMAIN}"
    certResolvers:
      letsencrypt:
        email: ${SECRET_ACME_EMAIL}
        dnsChallenge:
          provider: cloudflare
          resolvers:
            - 1.1.1.1
            - 9.9.9.9
