---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-traefik-certificates
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cert-manager-issuers
  path: ./kubernetes/apps/networking/traefik/certificates
  prune: true
  sourceRef:
    kind: GitRepository
    name: k0s-gitops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-traefik
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-traefik-certificates
  path: ./kubernetes/apps/networking/traefik/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k0s-gitops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---

# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-traefik-dashboard
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-traefik
    - name: cluster-apps-external-dns
  path: ./kubernetes/apps/networking/traefik/dashboard
  prune: true
  sourceRef:
    kind: GitRepository
    name: k0s-gitops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
