# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: database
    labels:
        cnpg.io/reload: "true"
stringData:
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:AXHsVBk1Xmc=,iv:cWHo5tbMmH5yMgec+RSh2teAqWsvcRHILfWrXY99NHU=,tag:/Q6EPI05Crw97Mky7ja8Ow==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:ZjoOnvMxJEmTq6wbHy40PFzm4pBq7qmSOEZp3wWIBQI=,iv:DEXposzExMlCYepHK/KjpUW74Nbo1WklgIi3zKujkOQ=,tag:SPX613M9Q7K78PYTXWwYiQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:L/oOSDPhZ2WIxumZcCHP4tZZ4g6yaTYK9bofT8cPF28=,iv:slt2EaOZ/V0ZvB2vQQT2A17k80hUvyru+x/G7XLUmQg=,tag:RyQXNlnFY1532xuyLlbvig==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:RSyzEDh1TLWYWIMy+iDU2e166yV7OJx5gSdVZH6R3ZEiFufcujVXBzrqcwefCgET+/2urzqEWsK7RpyiHtxseQ==,iv:qH5jYdAfTFmPZT0Yu3wnYrkqixVcGjObKgHVBcbp44w=,tag:BhMzZMgTO4mW65SS1/f/YQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1myxsdyjgwefpljpsvf0n6pvjr4n9ygz0nh3zy7wkfjnqdg54jayqwaqqfm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWjBlOTlhQnNFWDErQlM0
            ejBKYXpLTXRMN1JDWUJHL3F1R2FSU2ZaR0JvCkFaak1GdCswbWRuOEVJTXA3cFNi
            UC8zdDNidEZ6Rkp5bjQ5dTBhL0Rod0UKLS0tIHFHOE5VZDU4b01SeTZEVkdaemFW
            UU0yVGJ3N3NSYVlsVXZScGNvOHY5WjQKP0duP4eKEsD+GslnxYYwe4OGSIb/pa0T
            UoWNbAVKcl7eTM3lpAcq/bW8pofkRqHNEbO2j3mR0B78Oc9aRnYwIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-25T14:15:07Z"
    mac: ENC[AES256_GCM,data:Dcr0qEy+hNzMWb2G6bozZyT6aUEnko7nhkQXhhH2JQfkcGc1E0TgbtbGcT0+RkmE6mhxFyzLB5VnMyItmubaIG0F+7aZ8gE/bWpfGmpWHQ1hmd/F5rIJIGcmdXhOQWc18Q9oO3RngS5tSmvp2YUVRlGYwRGB5q8BC0Tdnkbmz3k=,iv:vFds9JcLqMppHLJ1Pfx0FEVMOBUX98kMr+Tch/Nhcc0=,tag:9mfaYfVDCjpPekN/wfrZig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
