# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: database
    labels:
        cnpg.io/reload: "true"
stringData:
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:5k2a5UQu1YA=,iv:pdE+O3hihO5Tpa1EFUWG1BXVzEzSoiIK5e3usyye2r0=,tag:+VG0m34IOImaMK9cNXrIaA==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:u6Sg+o37whNdc6jUJRYoO8bkzfzYvtZjokxoARLN9uc=,iv:3aL5hbqF5FqX37AqvOpvT5jcgh+I/Vdu3dCZAhnTL/k=,tag:cSMStUFrelg9FW1dBC7Vag==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:L/oOSDPhZ2WIxumZcCHP4tZZ4g6yaTYK9bofT8cPF28=,iv:slt2EaOZ/V0ZvB2vQQT2A17k80hUvyru+x/G7XLUmQg=,tag:RyQXNlnFY1532xuyLlbvig==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:RSyzEDh1TLWYWIMy+iDU2e166yV7OJx5gSdVZH6R3ZEiFufcujVXBzrqcwefCgET+/2urzqEWsK7RpyiHtxseQ==,iv:qH5jYdAfTFmPZT0Yu3wnYrkqixVcGjObKgHVBcbp44w=,tag:BhMzZMgTO4mW65SS1/f/YQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1myxsdyjgwefpljpsvf0n6pvjr4n9ygz0nh3zy7wkfjnqdg54jayqwaqqfm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWjBlOTlhQnNFWDErQlM0
            ejBKYXpLTXRMN1JDWUJHL3F1R2FSU2ZaR0JvCkFaak1GdCswbWRuOEVJTXA3cFNi
            UC8zdDNidEZ6Rkp5bjQ5dTBhL0Rod0UKLS0tIHFHOE5VZDU4b01SeTZEVkdaemFW
            UU0yVGJ3N3NSYVlsVXZScGNvOHY5WjQKP0duP4eKEsD+GslnxYYwe4OGSIb/pa0T
            UoWNbAVKcl7eTM3lpAcq/bW8pofkRqHNEbO2j3mR0B78Oc9aRnYwIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-25T19:19:20Z"
    mac: ENC[AES256_GCM,data:F0+K0yPICb+70hW9sWWPikhAAxz8hsYwBKYZvVVFLPoZ+QO2Df2P3EulIQDActbAidfxbWzW9bWbpnpaz/vJjoSdSDLp2ei3b8GT3bPli2lINx3qGHriOTHEDr145xasb/wwbzvB6IFLPuM17uWh6+78BSJWwA3IGuMdQfvSnxg=,iv:3NuBznJStLDziL5sQU5wIq/dwsg7J8pr1jWE0qikEhk=,tag:y9yDe59WTkwgiiPLn44BMA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
