---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gatus
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    initContainers:
      01-init-db:
        image: ghcr.io/onedr0p/postgres-init:14.8
        imagePullPolicy: IfNotPresent
        envFrom: &envFrom
          - secretRef:
              name: autobrr-secret
    controller:
      type: statefulset
    image:
      repository: ghcr.io/autobrr/autobrr
      tag: develop@sha256:cad1136b75f201565a992b6c5c7dd66d1bf287d461dc704d672a68936822b7d7
    env:
      AUTOBRR__CHECKFORUPDATES: "false"
      AUTOBRR__HOST: 0.0.0.0
      AUTOBRR__PORT: &port 8000
      AUTOBRR__LOGLEVEL: DEBUG
    envFrom: *envFrom
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: k0s.${SECRET_DOMAIN}
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
          traefik.ingress.kubernetes.io/router.middlewares: security-forwardauth-authelia@kubernetescrd
        hosts:
          - host: &host "{{ .Release.Name }}.devbu.io"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        enabled: true
        type: emptyDir
      config-file:
        enabled: true
        type: configMap
        name: autobrr-configmap
        subPath: config.toml
        mountPath: /config/config.toml
        readOnly: true
    resources:
      requests:
        memory: 250Mi
        cpu: 10m
      limits:
        memory: 500Mi
