---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lldap-gatus-ep
  namespace: security
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: lldap
        group: guarded
        url: https://lldap.${SECRET_DOMAIN}
        headers:
          Host: lldap.${SECRET_DOMAIN}
        interval: 1m
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
